# static map of reservoir ID
path_res: ../data/reservoirs/GloFAS/20220802_reservoirs_Global_03min.nc
# directory with the NetCDFs generated in the Lisflood run
path_ts: Z:/nahaUsers/casadje/GloFASv4/long_run/rsfil/
# variable of interest
var: rsfil
# directory where the extracted NetCDFs will be saved
path_out: Z:/nahaUsers/casadje/GloFASv4/US/rsfil/
period:
    start: 1982-01-02
    end: 2019-12-31