version: v3.0

paths:
    EFAS: 
        root: Z:/nahaUsers/casadje/EFASv5/ # E:/casadje/Documents/EFASv5/
        timeseries: #long_run/rsfil/
    GRanD: Z:/nahaUsers/casadje/datasets/reservoirs/GRanD/v1_3/
    dataset: 
        root: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsES/
        obs_timeseries: raw/time_series_all/
        sim_timeseries: ancillary/LISFLOOD/
        
normalize: False # normalize time series by reservoir storage capacity

period:
    start: 1990-01-01
    end: 2020-09-30

conditions:
    min_area: 25 # km²
    min_volume: 10 # hm3
    min_dor: 0.08 # degree of regulation
    min_dod: 0.06 # degree of disruptivity
    min_length: 8 # years
    tol_bias: 0.3 # relative bias accepted between inflow and outflow
