version: v1.0

url: https://www.ana.gov.br/sar0/MedicaoSIN

paths:
    LISFLOOD: 
        root: Z:/nahaUsers/casadje/GloFASv4/
        # timeseries: long_run/rsfil/
    GRanD: Z:/nahaUsers/casadje/datasets/reservoirs/GRanD/v1_3/
    ResOps: 
        root: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsBR/
        obs_timeseries: raw/time_series/SIN/
        sim_timeseries: ancillary/ncextract/

period:
    start: 1980-01-02
    end: 2020-01-01
    
normalize: True

conditions:
    min_area: 250 # km²
    min_volume: 10 # hm3
    min_dor: 0.08 # degree of regulation
    min_dod:
    min_years: 4 # years
    tol_bias: 0.3 # relative bias accepted between inflow and outflow
