data:
    path: /media/sf_nahaUsers/casadje/datasets/reservoirs/ResOpsUS/v1.1/
    reservoirs: reservoirs.txt
    periods: periods.pkl

simulation:
    model: mHM

calibration:
    # algorithm: SCEUA
    input:
        - inflow
    target:
        - outflow
    max_iter: 1000
    complexes: 4
    # train_size: 0.7
