data:
    path: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/v1.1/
    reservoirs: reservoirs_test.txt
    periods: periods.pkl
    
simulation:
    model: linear
    
calibration:
    # algorithm: SCEUA
    input:
        - inflow
    target:
        - storage
    max_iter: 1000
    complexes: 4
    # train_size: 0.7