data:
    path: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/v1.1/
    reservoirs: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/v1.1/selection/reservoirs.txt
    periods: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/v1.1/selection/periods.pkl
    
simulation:
    model: hanazaki
    
calibration:
    # algorithm: SCEUA
    input:
        - inflow
    target:
        - storage
    max_iter: 1000
    complexes: 4
    # train_size: 0.7