# # static map of reservoir ID
# path_res: ../../data/reservoirs/GloFAS/20220802_reservoirs_Global_03min.nc
# # directory with the NetCDFs generated in the Lisflood run
# path_ts: Z:/nahaUsers/casadje/GloFASv4/long_run/rsfil/
# # variable of interest
# var: rsfil
# # directory where the extracted NetCDFs will be saved
# path_out: Z:/nahaUsers/casadje/GloFASv4/US/rsfil/
# period:
#     start: 1982-01-02
#     end: 2019-12-31
    
    
paths:
    GloFAS: Z:/nahaUsers/casadje/GloFASv4/
    ResOpsUS: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/
    GRanD: Z:/nahaUsers/casadje/datasets/reservoirs/GRanD/v1_3/
    
extraction:
    path_in: Z:/nahaUsers/casadje/GloFASv4/long_run/
    variable: 
        - rsfil
    period:
        start: 1982-01-02
        end: 2019-12-31
    path_out: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/ancillary/ncextract/
    
simulation:


calibration:
    algorithm: SCEUA
    target:
        - storage
        - outflow
    max_iter: 1000
    complexes: 4
    train_size: 0.7
    path_out: ./calibration #/SCEUA/6parameters/bivariate/
    