data:
    path: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/v1.1/
    reservoirs: reservoirs.txt
    periods: periods.pkl

simulation:
    model: lisflood
    config:
        routine: 1
        limit_Q: True

calibration:
    # algorithm: SCEUA
    input:
        - inflow
    target:
        - storage
    max_iter: 1000
    complexes: 4
    # train_size: 0.7