paths:
    GloFAS: Z:/nahaUsers/casadje/GloFASv4/
    ResOpsUS: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/
    GRanD: Z:/nahaUsers/casadje/datasets/reservoirs/GRanD/v1_3/
    # static map of reservoir ID
    reservoirs: 
        netcdf: ../../data/reservoirs/GloFAS/20220802_reservoirs_Global_03min.nc
        shapefile: '../../GIS/reservoirs_analysis_US.shp'
    # directory with the NetCDFs generated in the Lisflood run
    timeseries: Z:/nahaUsers/casadje/GloFASv4/long_run/rsfil/
    dataset: Z:/nahaUsers/casadje/datasets/reservoirs/

# variable of interest
var: rsfil
# directory where the extracted NetCDFs will be saved
path_out: Z:/nahaUsers/casadje/GloFASv4/US/rsfil/
# period:
#     start: 1982-01-02
#     end: 2019-12-31
    
simulation:
    model: lisflood
    config:
        limit_Q: True
        routine: 5
        k: 2
    
calibration:
    algorithm: SCEUA
    target:
        - storage
        - outflow
    max_iter: 1000
    complexes: 4
    train_size: 0.7
    path_out: ./calibration