# Example of the configuration file need to run functions `simulate` and `calibrate`.
# In this example, we will use the mHM reservoir routine and calibrate it using "storage" as the target variable.

data:
    path: /PATH_ROOT/ResOpsUS/v2.0/
    reservoirs: /PATH_ROOT/ResOpsUS/v2.0/selection/reservoirs.txt
    periods: /PATH_ROOT/ResOpsUS/v2.0/selection/periods.pkl
    results: /PATH_ROOT/ResOpsUS/v2.0/results/
    
simulation:
    model: mhm
    inputs: # names of the time series
        inflow: inflow # compulsory (m3/s). By default, 'inflow'
        precipitation:  # optional (mm). By default, None
        evaporation: # optional (mm). By default, None
        demand: # optional (m3). By default, None
    spinup: # time steps. By default, None

calibration:
    target:
        - storage
        # - outflow
    SCEUA:
        max_iter: 5000
        complexes: 16
        kstop: 5 # number of generations without performance improvement
        peps: 0.01 # absolute improvement in performance to keep interating
        pcento: 0.001 # relative improvement in performance to keep iterating