# Example of the configuration file need to run functions `simulate` and `calibrate`.
# In this example, we will use the mHM reservoir routine and calibrate it using "storage" as the target variable.

data:
    path: /PATH_ROOT/ResOpsUS/v2.0/
    reservoirs: /PATH_ROOT/ResOpsUS/v2.0/selection/reservoirs.txt
    periods: /PATH_ROOT/ResOpsUS/v2.0/selection/periods.pkl

simulation:
    model: mhm
    # only needed for the Lisflood routine
    # config:
        # routine: 1
        # limit_Q: True
    path: /PATH_ROOT/ResOpsUS/v2.0/results/

calibration:
    input:
        - inflow
    target:
        - storage
    max_iter: 1000
    complexes: 4
    path: /PATH_ROOT/ResOpsUS/v2.0/results/
