# Example of the configuration file need to run functions `simulate` and `calibrate`.
# In this example, we will use the mHM reservoir routine and calibrate it using "storage" as the target variable.

data:
    path: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/v1.1/
    reservoirs: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/v1.1/selection/reservoirs.txt
    periods: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/v1.1/selection/periods.pkl

simulation:
    model: mhm
    # only needed for the Lisflood routine
    # config:
        # routine: 1
        # limit_Q: True
    path: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/results/

calibration:
    input:
        - inflow
    target:
        - storage
    max_iter: 1000
    complexes: 4
    path: Z:/nahaUsers/casadje/datasets/reservoirs/ResOpsUS/results/
