# Example of the configuration file need to run functions `simulate` and `calibrate`.
# In this example, we will use the mHM reservoir routine and calibrate it using "storage" as the target variable.

data:
    path: /PATH_ROOT/ResOpsUS/v2.0/
    reservoirs: /PATH_ROOT/ResOpsUS/v2.0/selection/reservoirs.txt
    periods: /PATH_ROOT/ResOpsUS/v2.0/selection/periods.pkl
    results: /PATH_ROOT/ResOpsUS/v2.0/results/
    
simulation:
    model: mhm
    # only needed for the Lisflood routine
    # config:
        # routine: 1
        # limit_Q: True

calibration:
    input:
        - inflow
    target:
        - storage
    SCEUA:
        max_iter: 1000
        complexes: 4
