# Example of the configuration file need to run functions `simulate` and `calibrate`.
# In this example, we will use the mHM reservoir routine and calibrate it using "storage" as the target variable.

data:
    path: /PATH_ROOT/ResOpsUS/v2.0/
    reservoirs: /PATH_ROOT/ResOpsUS/v2.0/selection/reservoirs.txt
    periods: /PATH_ROOT/ResOpsUS/v2.0/selection/periods.pkl
    results: /PATH_ROOT/ResOpsUS/v2.0/results/
    
simulation:
    model: mhm
    inputs: # names of the time series
        inflow: inflow # compulsory (m3/s). By default, 'inflow'
        precipitation:  # optional (mm). By default, None
        evaporation: # optional (mm). By default, None
        demand: # optional (m3). By default, None

calibration:
    target:
        - storage
    SCEUA:
        max_iter: 1000
        complexes: 4
        spinup: # time steps. By default, None
